### ISSUE TITLE
Plugin is not getting enabled under bitbucket version 4.5.1

### ISSUE THREAD

**Issue by RaviFIS** [tomasbjerre/pull-request-notifier-for-bitbucket#112]
Hi

2016-04-27 10:56:42,008 ERROR [http-nio-7990-exec-4] xxxx @1PWA01Ox656x81x0 12pbhr8 x.xxx.xx.xxxx "PUT /rest/plugins/1.0/se.bjurr.prnfs.pull-request-notifier-for-stash-key HTTP/1.1" c.a.plugin.manager.PluginEnabler Unable to enable plugin se.bjurr.prnfs.pull-request-notifier-for-stash
com.atlassian.plugin.osgi.container.OsgiContainerException: Cannot start plugin: se.bjurr.prnfs.pull-request-notifier-for-stash
        at com.atlassian.plugin.osgi.factory.OsgiPlugin.enableInternal(OsgiPlugin.java:418) ~[atlassian-plugins-osgi-4.1.1.jar:na]
        at com.atlassian.plugin.impl.AbstractPlugin.enable(AbstractPlugin.java:286) ~[atlassian-plugins-core-4.1.1.jar:na]
        at com.atlassian.plugin.manager.PluginEnabler.actualEnable(PluginEnabler.java:130) [atlassian-plugins-core-4.1.1.jar:na]
        at com.atlassian.plugin.manager.PluginEnabler.enable(PluginEnabler.java:107) [atlassian-plugins-core-4.1.1.jar:na]
        at com.atlassian.plugin.manager.PluginEnabler.enableAllRecursively(PluginEnabler.java:79) [atlassian-plugins-core-4.1.1.jar:na]
        at com.atlassian.plugin.manager.DefaultPluginManager.enablePlugins(DefaultPluginManager.java:1657) [atlassian-plugins-core-4.1.1.jar:na]
        at com.atlassian.stash.internal.plugin.ClusteredPluginController.enablePlugins(ClusteredPluginController.java:55) [bitbucket-platform-4.5.2.jar:na]
        at com.atlassian.plugin.util.ContextClassLoaderSettingInvocationHandler.invoke(ContextClassLoaderSettingInvocationHandler.java:26) [atlassian-plugins-core-4.1.1.jar:na]
        at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.doInvoke(ServiceInvoker.java:56) [gemini-blueprint-core-2.0.0.BUILD-atlassian-m002.jar:2.0.0.BUILD-atlassian-m002]
        at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.invoke(ServiceInvoker.java:60) [gemini-blueprint-core-2.0.0.BUILD-atlassian-m002.jar:2.0.0.BUILD-atlassian-m002]
        at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invokeUnprivileged(ServiceTCCLInterceptor.java:70) [gemini-blueprint-core-2.0.0.BUILD-atlassian-m002.jar:2.0.0.BUILD-atlassian-m002]
        at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invoke(ServiceTCCLInterceptor.java:53) [gemini-blueprint-core-2.0.0.BUILD-atlassian-m002.jar:2.0.0.BUILD-atlassian-m002]
        at org.eclipse.gemini.blueprint.service.importer.support.LocalBundleContextAdvice.invoke(LocalBundleContextAdvice.java:57) [gemini-blueprint-core-2.0.0.BUILD-atlassian-m002.jar:2.0.0.BUILD-atlassian-m002]
        at com.atlassian.upm.core.impl.PluginEnablementServiceImpl$1.doInTransaction(PluginEnablementServiceImpl.java:87) [atlassian-universal-plugin-manager-plugin-2.20.4_1460529430000.jar:na]
        at com.atlassian.upm.core.impl.PluginEnablementServiceImpl$1.doInTransaction(PluginEnablementServiceImpl.java:63) [atlassian-universal-plugin-manager-plugin-2.20.4_1460529430000.jar:na]
        at com.atlassian.sal.core.transaction.HostContextTransactionTemplate$1.doInTransaction(HostContextTransactionTemplate.java:21) [sal-core-3.0.5.jar:na]
        at com.atlassian.stash.internal.sal.spi.HostContextAccessorImpl.doInTransaction(HostContextAccessorImpl.java:54) [bitbucket-platform-4.5.2.jar:na]
        at com.atlassian.plugin.util.ContextClassLoaderSettingInvocationHandler.invoke(ContextClassLoaderSettingInvocationHandler.java:26) [atlassian-plugins-core-4.1.1.jar:na]
        at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.doInvoke(ServiceInvoker.java:56) [gemini-blueprint-core-2.0.0.BUILD-atlassian-m002.jar:2.0.0.BUILD-atlassian-m002]
        at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.invoke(ServiceInvoker.java:60) [gemini-blueprint-core-2.0.0.BUILD-atlassian-m002.jar:2.0.0.BUILD-atlassian-m002]
        at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invokeUnprivileged(ServiceTCCLInterceptor.java:70) [gemini-blueprint-core-2.0.0.BUILD-atlassian-m002.jar:2.0.0.BUILD-atlassian-m002]
        at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invoke(ServiceTCCLInterceptor.java:53) [gemini-blueprint-core-2.0.0.BUILD-atlassian-m002.jar:2.0.0.BUILD-atlassian-m002]
        at org.eclipse.gemini.blueprint.service.importer.support.LocalBundleContextAdvice.invoke(LocalBundleContextAdvice.java:57) [gemini-blueprint-core-2.0.0.BUILD-atlassian-m002.jar:2.0.0.BUILD-atlassian-m002]
        at com.atlassian.sal.core.transaction.HostContextTransactionTemplate.execute(HostContextTransactionTemplate.java:18) [sal-core-3.0.5.jar:na]
        at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.doInvoke(ServiceInvoker.java:56) [gemini-blueprint-core-2.0.0.BUILD-atlassian-m002.jar:2.0.0.BUILD-atlassian-m002]
        at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.invoke(ServiceInvoker.java:60) [gemini-blueprint-core-2.0.0.BUILD-atlassian-m002.jar:2.0.0.BUILD-atlassian-m002]
        at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invokeUnprivileged(ServiceTCCLInterceptor.java:70) [gemini-blueprint-core-2.0.0.BUILD-atlassian-m002.jar:2.0.0.BUILD-atlassian-m002]
        at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invoke(ServiceTCCLInterceptor.java:53) [gemini-blueprint-core-2.0.0.BUILD-atlassian-m002.jar:2.0.0.BUILD-atlassian-m002]
        at org.eclipse.gemini.blueprint.service.importer.support.LocalBundleContextAdvice.invoke(LocalBundleContextAdvice.java:57) [gemini-blueprint-core-2.0.0.BUILD-atlassian-m002.jar:2.0.0.BUILD-atlassian-m002]
        at com.atlassian.upm.core.impl.PluginEnablementServiceImpl.enablePlugin(PluginEnablementServiceImpl.java:62) [atlassian-universal-plugin-manager-plugin-2.20.4_1460529430000.jar:na]
        at com.atlassian.upm.core.rest.resources.PluginResource.put(PluginResource.java:122) [atlassian-universal-plugin-manager-plugin-2.20.4_1460529430000.jar:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) [applinks-plugin-5.0.5_1460529418000.jar:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) [applinks-plugin-5.0.5_1460529418000.jar:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) [applinks-plugin-5.0.5_1460529418000.jar:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) [applinks-plugin-5.0.5_1460529418000.jar:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) [applinks-plugin-5.0.5_1460529418000.jar:na]
        at com.atlassian.plugin.connect.plugin.auth.scope.ApiScopingFilter.doFilter(ApiScopingFilter.java:89) [atlassian-connect-plugin-1.1.70-bitbucket-01.jar:na]
        at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:88) [classes/:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:109) [classes/:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75) [classes/:na]
        at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:94) [atlassian-trusted-apps-core-4.2.0.jar:na]
        at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:67) [atlassian-oauth-service-provider-plugin-2.0.3_1460529420000.jar:na]
        at com.atlassian.core.filters.ServletContextThreadLocalFilter.doFilter(ServletContextThreadLocalFilter.java:21) [atlassian-core-4.6.19.jar:na]
        at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:31) [atlassian-core-4.6.19.jar:na]
        at com.atlassian.plugin.connect.plugin.auth.user.ThreeLeggedAuthFilter.doFilter(ThreeLeggedAuthFilter.java:122) [atlassian-connect-plugin-1.1.70-bitbucket-01.jar:na]
        at com.atlassian.plugin.connect.plugin.auth.oauth.OAuth2LOFilter.doFilter(OAuth2LOFilter.java:82) [atlassian-connect-plugin-1.1.70-bitbucket-01.jar:na]
        at com.atlassian.jwt.internal.servlet.JwtAuthFilter.doFilter(JwtAuthFilter.java:32) [jwt-plugin-1.5.5_1460529420000.jar:na]
        at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:38) [analytics-client-5.2.1_1460529416000.jar:na]
        at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:39) [analytics-client-5.2.1_1460529416000.jar:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:87) [classes/:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:73) [classes/:na]
        at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:86) [bitbucket-service-impl-4.5.2.jar:na]
        at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38) [classes/:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
        ... 300 frames trimmed
Caused by: org.osgi.framework.BundleException: Unresolved constraint in bundle se.bjurr.prnfs.pull-request-notifier-for-stash [114]: Unable to resolve 114.0: missing requirement [114.0] osgi.wiring.package; (osgi.wiring.package=com.atlassian.stash.repository)
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:3974) ~[org.apache.felix.framework-4.2.1.jar:na]
        ... 55 common frames omitted
2016-04-27 10:56:46,812 WARN  [localScheduler_Worker-1]  c.a.a.c.h.r.RemoteHashingInstructionsReader Unable to read remote instructions with key 'uid.onewayhash'.
2016-04-27 10:56:46,812 WARN  [localScheduler_Worker-1]  c.a.a.c.h.BcryptAnalyticsEmailHasher No instructions for hashing could be found.

Is the plugin suppose to work for the latest version of bibucket ?

Thanks
Ravi.

**Comment by tomasbjerre** [comment]
It should work. What is the version of the plugin and what is the version of Bitbucket Server?

**Comment by RaviFIS** [comment]
I already mentioned Bitbucket server version in the  issue subject line it is the latest 4.5.1  where as plugin edition we are using is 1.37

Ravi.

**Comment by RaviFIS** [comment]
I am sorry the bitbucket version is 4.5.2

**Comment by tomasbjerre** [comment]
Ok. 1.x is only compatible with Stash. 2.x is compatible with Bitbucket
server.
Den 27 apr 2016 18:13 skrev "RaviFIS" <notifications@github.com>:

**Comment by RaviFIS** [comment]
My bad.  I should have checked the market place. Sorry to bother you.

**Comment by RaviFIS** [comment]
So if we upgrade the changes to the hooks we made remains ?

**Comment by tomasbjerre** [comment]
No problem :)
Den 27 apr 2016 18:24 skrev "RaviFIS" <notifications@github.com>:

**Comment by tomasbjerre** [comment]
They should remain. I dont recall anyone reporting issues with settings being absent after upgrade. But I dont promise anything =)
