### ISSUE TITLE
All buttons disappear if any associated repo is deleted

### ISSUE THREAD

**Issue by kashyapparikh-ck** [tomasbjerre/pull-request-notifier-for-bitbucket#160]
Bitbucket version: 4.9.1
PRNFB Version: 2.37
To reproduce:
- Add 2 buttons on 2 separate repos
   - first button under global config for PRNFB plugin
   - second button under repo level config for PRNFB plugin 
- Delete the repo under which second button was added
- Notice that the first button no longer shows up (for all non-admin bitbucket users)
The root cause is that the config associated with second button is left dangling and UserCheckService throws NullPointer for missing repo `repository is null`.

I fixed it by removing the second button config from global config, which is an issue in itself. Should repo level configs for PRNFB plugin show up in global config?

Here's partial stack that showed up in Bitbucket log when browsing to repo that had first button
```
2016-11-07 07:24:50,328 ERROR [http-nio-7990-exec-2] user.name *AAABBBCCCDDDx1 1zzzzz 10.10.20.20,10.10.20.30 "GET /rest/prnfb-admin/1.0/settings/buttons/repository/1238/pullrequest/11 HTTP/1.1" c.a.p.r.c.e.j.ThrowableExceptionMapper Uncaught exception thrown by REST service: Repository is null
java.lang.NullPointerException: Repository is null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226) ~[guava-18.0.jar:na]
        at com.atlassian.stash.internal.CommonValidations.validateRepository(CommonValidations.java:70) ~[bitbucket-service-impl-4.9.1.jar:na]
        at com.atlassian.stash.internal.user.PermissionServiceImpl.hasRepositoryPermission(PermissionServiceImpl.java:618) ~[bitbucket-service-impl-4.9.1.jar:na]
        at com.atlassian.stash.internal.user.PermissionServiceImpl.hasRepositoryPermission(PermissionServiceImpl.java:300) ~[bitbucket-service-impl-4.9.1.jar:na]
        at com.atlassian.plugin.util.ContextClassLoaderSettingInvocationHandler.invoke(ContextClassLoaderSettingInvocationHandler.java:26) ~[atlassian-plugins-core-4.2.4.jar:na]
        at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.doInvoke(ServiceInvoker.java:56) ~[na:na]
        at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.invoke(ServiceInvoker.java:60) ~[na:na]
        at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invokeUnprivileged(ServiceTCCLInterceptor.java:70) ~[na:na]
        at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invoke(ServiceTCCLInterceptor.java:53
```

**Comment by tomasbjerre** [comment]
This looks like same stacktrace as in https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/issues/154 and that was just fixed in 2.40.

And yes, the idea is that global config shows everything. It has the drop down menus for selecting project/repo. The repo level config does not have this drop down.

**Comment by kashyapparikh-ck** [comment]
As always, thank you Tomas for your quick response! I will give new version a shot.

Question: This means button config will need to be removed separately if underlying repo is deleted?

**Comment by tomasbjerre** [comment]
Thanks :) And yes thats true.

Den 16 nov. 2016 23:17 skrev "kashyapparikh-ck" <notifications@github.com>:
