### ISSUE TITLE
Can not recieve events with Bitbucket Server on trial license

### ISSUE THREAD

**Issue by vinokurig** [tomasbjerre/pull-request-notifier-for-bitbucket#167]
I have a trial license in Bitbucket Server and I do not receive requests on any event. Is it support using trial license?

**Comment by tomasbjerre** [comment]
Dont know. It sounds strange.

**Comment by vinokurig** [comment]
This is what I have in logs:
```
2016-12-09 09:43:05,087 INFO  [http-nio-7990-exec-6] ivinokur @T70CD7x583x9375x0 5g8zb6 193.108.249.4 "POST /rest/prnfb-admin/1.0/settings/buttons/0ab27544-eee2-46ae-acef-2a575630c41f/p
ress/repository/2/pullrequest/46 HTTP/1.1" se.bjurr.prnfb.http.UrlInvoker Url: "https://aio.codenvy-dev.com/api/system/ram/limit"
2016-12-09 09:44:28,678 DEBUG [http-nio-7990-exec-9] ivinokur @T70CD7x584x9376x1 5g8zb6 193.108.249.4 "GET /rest/mirroring/latest/repos/2/mirrors HTTP/1.1" c.a.s.i.r.e.ServiceExceptionM
apper Mapping ServiceException to REST response 409
com.atlassian.bitbucket.mirroring.upstream.MirroringDisabledException: Mirroring requires a Bitbucket Data Center license.
        at com.atlassian.bitbucket.internal.mirroring.upstream.DefaultSmartMirroringFeature.checkEnabled(DefaultSmartMirroringFeature.java:33) ~[bitbucket-mirroring-upstream-4.11.0.jar:
na]
        at com.atlassian.bitbucket.internal.mirroring.upstream.DefaultMirrorService.findAll(DefaultMirrorService.java:94) ~[bitbucket-mirroring-upstream-4.11.0.jar:na]
        at com.atlassian.bitbucket.internal.mirroring.upstream.rest.RepositoryResource.getRepositoryMirrors(RepositoryResource.java:121) ~[bitbucket-mirroring-upstream-4.11.0.jar:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.4_1478241564000.jar:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.4_1478241564000.jar:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.4_1478241564000.jar:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.4_1478241564000.jar:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.4_1478241564000.jar:na]
        at com.atlassian.analytics.client.filter.UniversalAnalyticsFilter.doFilter(UniversalAnalyticsFilter.java:92) [analytics-client-5.2.20_1478241564000.jar:na]
        at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:39) [analytics-client-5.2.20_1478241564000.jar:na]
        at com.atlassian.plugin.connect.plugin.auth.scope.ApiScopingFilter.doFilter(ApiScopingFilter.java:81) [atlassian-connect-plugin-1.1.86-bitbucket-04.jar:na]
        at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:88) [classes/:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:109) [classes/:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75) [classes/:na]
        at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:94) [atlassian-trusted-apps-core-4.2.0.jar:na]
        at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:67) [atlassian-oauth-service-provider-plugin-2.0.3_1478241564000.jar:na]
        at com.atlassian.core.filters.ServletContextThreadLocalFilter.doFilter(ServletContextThreadLocalFilter.java:21) [atlassian-core-4.6.19.jar:na]
        at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:31) [atlassian-core-4.6.19.jar:na]
        at com.atlassian.plugin.connect.plugin.auth.user.ThreeLeggedAuthFilter.doFilter(ThreeLeggedAuthFilter.java:109) [atlassian-connect-plugin-1.1.86-bitbucket-04.jar:na]
        at com.atlassian.jwt.internal.servlet.JwtAuthFilter.doFilter(JwtAuthFilter.java:32) [jwt-plugin-1.5.11-0002_1478241564000.jar:na]
        at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:38) [analytics-client-5.2.20_1478241564000.jar:na]
        at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:39) [analytics-client-5.2.20_1478241564000.jar:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:87) [classes/:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:73) [classes/:na]
        at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:83) ~[bitbucket-service-impl-4.11.0.jar:na]
        at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38) ~[classes/:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]
        ... 233 frames trimmed
2016-12-09 09:45:12,430 ERROR [http-nio-7990-exec-6] ivinokur @T70CD7x583x9375x0 5g8zb6 193.108.249.4 "POST /rest/prnfb-admin/1.0/settings/buttons/0ab27544-eee2-46ae-acef-2a575630c41f/p
ress/repository/2/pullrequest/46 HTTP/1.1" se.bjurr.prnfb.http.UrlInvoker
org.apache.http.conn.ConnectTimeoutException: Connect to aio.codenvy-dev.com:443 [aio.codenvy-dev.com/192.168.65.2] failed: Connection timed out
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:149) ~[httpclient-4.5.1.jar:4.5.1]
        at org.apache.http.impl.conn.BasicHttpClientConnectionManager.connect(BasicHttpClientConnectionManager.java:338) ~[httpclient-4.5.1.jar:4.5.1]
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[httpclient-4.5.1.jar:4.5.1]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.1.jar:4.5.1]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[httpclient-4.5.1.jar:4.5.1]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[httpclient-4.5.1.jar:4.5.1]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.1.jar:4.5.1]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.5.1.jar:4.5.1]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.5.1.jar:4.5.1]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107) ~[httpclient-4.5.1.jar:4.5.1]
        at se.bjurr.prnfb.http.UrlInvoker.doInvoke(UrlInvoker.java:344) [plugin.784252979288209347.pull-request-notifier-for-bitbucket-2.41_1481131291000.jar:na]
        at se.bjurr.prnfb.http.UrlInvoker.invoke(UrlInvoker.java:163) [plugin.784252979288209347.pull-request-notifier-for-bitbucket-2.41_1481131291000.jar:na]
        at se.bjurr.prnfb.listener.PrnfbPullRequestEventListener$1.invoke(PrnfbPullRequestEventListener.java:90) [plugin.784252979288209347.pull-request-notifier-for-bitbucket-2.41_1481
131291000.jar:na]
        at se.bjurr.prnfb.listener.PrnfbPullRequestEventListener.notify(PrnfbPullRequestEventListener.java:197) [plugin.784252979288209347.pull-request-notifier-for-bitbucket-2.41_14811
31291000.jar:na]
        at se.bjurr.prnfb.service.ButtonsService.doHandlePressed(ButtonsService.java:117) [plugin.784252979288209347.pull-request-notifier-for-bitbucket-2.41_1481131291000.jar:na]
        at se.bjurr.prnfb.service.ButtonsService.handlePressed(ButtonsService.java:62) [plugin.784252979288209347.pull-request-notifier-for-bitbucket-2.41_1481131291000.jar:na]
        at se.bjurr.prnfb.presentation.ButtonServlet.press(ButtonServlet.java:159) [plugin.784252979288209347.pull-request-notifier-for-bitbucket-2.41_1481131291000.jar:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.4_1478241564000.jar:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.4_1478241564000.jar:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.4_1478241564000.jar:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.4_1478241564000.jar:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.4_1478241564000.jar:na]
        at com.atlassian.analytics.client.filter.UniversalAnalyticsFilter.doFilter(UniversalAnalyticsFilter.java:92) [analytics-client-5.2.20_1478241564000.jar:na]
        at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:39) [analytics-client-5.2.20_1478241564000.jar:na]
        at com.atlassian.plugin.connect.plugin.auth.scope.ApiScopingFilter.doFilter(ApiScopingFilter.java:81) [atlassian-connect-plugin-1.1.86-bitbucket-04.jar:na]
        at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:88) [classes/:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:109) [classes/:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75) [classes/:na]
        at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:94) [atlassian-trusted-apps-core-4.2.0.jar:na]
        at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:67) [atlassian-oauth-service-provider-plugin-2.0.3_1478241564000.jar:na]
        at com.atlassian.core.filters.ServletContextThreadLocalFilter.doFilter(ServletContextThreadLocalFilter.java:21) [atlassian-core-4.6.19.jar:na]
        at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:31) [atlassian-core-4.6.19.jar:na]
        at com.atlassian.plugin.connect.plugin.auth.user.ThreeLeggedAuthFilter.doFilter(ThreeLeggedAuthFilter.java:109) [atlassian-connect-plugin-1.1.86-bitbucket-04.jar:na]
        at com.atlassian.jwt.internal.servlet.JwtAuthFilter.doFilter(JwtAuthFilter.java:32) [jwt-plugin-1.5.11-0002_1478241564000.jar:na]
        at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:38) [analytics-client-5.2.20_1478241564000.jar:na]
        at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:39) [analytics-client-5.2.20_1478241564000.jar:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:87) [classes/:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:73) [classes/:na]
        at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:83) ~[bitbucket-service-impl-4.11.0.jar:na]
        at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38) ~[classes/:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]
        ... 233 frames trimmed
Caused by: java.net.ConnectException: Connection timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_102]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_102]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_102]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_102]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_102]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_102]
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:337) ~[httpclient-4.5.1.jar:4.5.1]
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134) ~[httpclient-4.5.1.jar:4.5.1]
        ... 42 common frames omitted
```

May be this is some how related to this:
```
2016-12-09 09:44:28,678 DEBUG [http-nio-7990-exec-9] ivinokur @T70CD7x584x9376x1 5g8zb6 193.108.249.4 "GET /rest/mirroring/latest/repos/2/mirrors HTTP/1.1" c.a.s.i.r.e.ServiceExceptionM
apper Mapping ServiceException to REST response 409
```
This exception appears exactly after invoking my request url.
@tomasbjerre What do you think?

**Comment by tomasbjerre** [comment]
Looks like the Bitbucket Server machine cannot reach aio.codenvy-dev.com:443. Connection timed out. So the plugin is working fine.

**Comment by vinokurig** [comment]
OK, thanks for help
