### ISSUE TITLE
UrlInvoker.doInvoke Throws Unknown Exception

### ISSUE THREAD

**Issue by pgreen1014** [tomasbjerre/pull-request-notifier-for-bitbucket#177]
I am trying to set up this plugin to work with TeamCity; however, I am getting the following error stacktrace from our bitbucket log:

`2016-12-28 09:41:46,403 ERROR [threadpool:thread-1] buildbot @15Q07FLx581x64247404x0 i1paw 192.168.48.51,172.17.42.1 "POST /rest/api/latest/projects/test/repos/repo/pull-requests/268/reopen HTTP/1.1" se.bjurr.prnfb.http.UrlInvoker 
	at se.bjurr.prnfb.http.UrlInvoker.doInvoke(UrlInvoker.java:352) [plugin.4464963591233580878.pull-request-notifier-for-bitbucket-2.45_1482853392000.jar:na]
	at se.bjurr.prnfb.http.UrlInvoker.invoke(UrlInvoker.java:164) [plugin.4464963591233580878.pull-request-notifier-for-bitbucket-2.45_1482853392000.jar:na]
	at se.bjurr.prnfb.listener.PrnfbPullRequestEventListener$1.invoke(PrnfbPullRequestEventListener.java:94) [plugin.4464963591233580878.pull-request-notifier-for-bitbucket-2.45_1482853392000.jar:na]
	at se.bjurr.prnfb.listener.PrnfbPullRequestEventListener.notify(PrnfbPullRequestEventListener.java:263) [plugin.4464963591233580878.pull-request-notifier-for-bitbucket-2.45_1482853392000.jar:na]
	at se.bjurr.prnfb.listener.PrnfbPullRequestEventListener.handleEvent(PrnfbPullRequestEventListener.java:116) [plugin.4464963591233580878.pull-request-notifier-for-bitbucket-2.45_1482853392000.jar:na]
	at se.bjurr.prnfb.listener.PrnfbPullRequestEventListener.access$000(PrnfbPullRequestEventListener.java:60) [plugin.4464963591233580878.pull-request-notifier-for-bitbucket-2.45_1482853392000.jar:na]
	at se.bjurr.prnfb.listener.PrnfbPullRequestEventListener$2.run(PrnfbPullRequestEventListener.java:132) [plugin.4464963591233580878.pull-request-notifier-for-bitbucket-2.45_1482853392000.jar:na]`

The error is coming from URLInvoker.doInvoke's builder.build().execute(httpRequestBase) on line 352.

Everything works fine when I run it through a proxy (charles proxy). For some reason it is only when trying to trigger directly from the plugin to our TeamCity server that it doesn't work.

**Here are the configurations I tried**
![config-1 0](https://cloud.githubusercontent.com/assets/13759662/21548028/2f21ba8a-cdaf-11e6-8140-e42277d7c6e5.png)
![config-1 2](https://cloud.githubusercontent.com/assets/13759662/21548029/30737e8c-cdaf-11e6-86ea-99720b38001e.png)
![config-2 1](https://cloud.githubusercontent.com/assets/13759662/21548030/32006260-cdaf-11e6-9706-10565f00d6cc.png)
![config-2 2](https://cloud.githubusercontent.com/assets/13759662/21548031/337acba8-cdaf-11e6-92a9-d3369a8f746b.png)

**Comment by tomasbjerre** [comment]
"Everything works fine when I run it through a proxy (charles proxy)."

Does that mean the plugin can trigger TC when you fill in the proxy information in the plugin?

If you logon the the server running Bitbucket Server (perhaps SSH) and issue a `curl` command from there. Does that work?

**Comment by pgreen1014** [comment]
whoops, I overlooked the remaining stacktace in my terminal, here is the rest of it: 

`java.net.UnknownHostException: local_sercer: unknown error
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_91]
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[na:1.8.0_91]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[na:1.8.0_91]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276) ~[na:1.8.0_91]
	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[na:1.8.0_91]
	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[na:1.8.0_91]
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:111) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107) ~[httpclient-4.5.1.jar:4.5.1]
	at se.bjurr.prnfb.http.UrlInvoker.doInvoke(UrlInvoker.java:352) [plugin.4464963591233580878.pull-request-notifier-for-bitbucket-2.45_1482853392000.jar:na]
	at se.bjurr.prnfb.http.UrlInvoker.invoke(UrlInvoker.java:164) [plugin.4464963591233580878.pull-request-notifier-for-bitbucket-2.45_1482853392000.jar:na]
	at se.bjurr.prnfb.listener.PrnfbPullRequestEventListener$1.invoke(PrnfbPullRequestEventListener.java:94) [plugin.4464963591233580878.pull-request-notifier-for-bitbucket-2.45_1482853392000.jar:na]
	at se.bjurr.prnfb.listener.PrnfbPullRequestEventListener.notify(PrnfbPullRequestEventListener.java:263) [plugin.4464963591233580878.pull-request-notifier-for-bitbucket-2.45_1482853392000.jar:na]
	at se.bjurr.prnfb.listener.PrnfbPullRequestEventListener.handleEvent(PrnfbPullRequestEventListener.java:116) [plugin.4464963591233580878.pull-request-notifier-for-bitbucket-2.45_1482853392000.jar:na]
	at se.bjurr.prnfb.listener.PrnfbPullRequestEventListener.access$000(PrnfbPullRequestEventListener.java:60) [plugin.4464963591233580878.pull-request-notifier-for-bitbucket-2.45_1482853392000.jar:na]
	at se.bjurr.prnfb.listener.PrnfbPullRequestEventListener$2.run(PrnfbPullRequestEventListener.java:132) [plugin.4464963591233580878.pull-request-notifier-for-bitbucket-2.45_1482853392000.jar:na]
	at com.atlassian.stash.internal.concurrent.StateTransferringExecutor$StateTransferringRunnable.run(StateTransferringExecutor.java:70) [bitbucket-platform-4.6.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_91]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_91]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]`

Seems to be caused by an UnknowHostException. And yes filling in the proxy information in the plugin triggered the build in TeamCity. I don't think I have access to our Bitbucket Server, I will have to see about that.

**Comment by tomasbjerre** [comment]
Could it be that server is misspelled in local_sercer?

Den 29 dec. 2016 5:44 PM skrev "pgreen1014" <notifications@github.com>:

**Comment by pgreen1014** [comment]
No, I substituted our server name with "local_sercer" for submitting this issue, but the actual spelling is correct on my end.

**Comment by itay** [comment]
I've seen an issue like this before when the host BB was running on wasn't properly resolving the DNS name or Java wasn't. See what happens if you try putting the IP address. Also try a ping to see if it can even connect to it directly.

**Comment by pgreen1014** [comment]
I received new logs and found a ConnectTimeOutException which is due to our TeamCity server being on a different network from our Bitbucket server which is unable to access the TeamCity server. Closing this issue.
