### ISSUE TITLE
Injection URL does not allow variables

### ISSUE THREAD

**Issue by schubter** [tomasbjerre/pull-request-notifier-for-bitbucket#208]
* Plugin version used.
2.60
 * Bitbucket Server version used.
4.13.0
 * Stack traces in Bitbucket Server log file.
`
2017-03-24 09:49:54,495 ERROR [http-apr-7990-exec-2]  192.168.178.105,192.168.178.11 "POST /rest/prnfb-admin/1.0/settings/buttons/d9ecab68-9cab-43bc-aa05-57391abac4e7/press/repository/253/pullrequest/21 HTTP/1.1" se.bjurr.prnfb.service.PrnfbRenderer Error when resolving INJECTION_URL_VALUE
java.util.regex.PatternSyntaxException: Illegal repetition near index 12
/shortName="${PULL_REQUEST_FROM_BRANCH}" shortKey=["']([^'"]+)/g
            ^
	at java.util.regex.Pattern.error(Pattern.java:1955) ~[na:1.8.0_111]
	at java.util.regex.Pattern.closure(Pattern.java:3157) ~[na:1.8.0_111]
	at java.util.regex.Pattern.sequence(Pattern.java:2134) ~[na:1.8.0_111]
	at java.util.regex.Pattern.expr(Pattern.java:1996) ~[na:1.8.0_111]
	at java.util.regex.Pattern.compile(Pattern.java:1696) ~[na:1.8.0_111]
	at java.util.regex.Pattern.<init>(Pattern.java:1351) ~[na:1.8.0_111]
	at java.util.regex.Pattern.compile(Pattern.java:1028) ~[na:1.8.0_111]
	at se.bjurr.prnfb.service.PrnfbVariable$3.resolve(PrnfbVariable.java:124) ~[plugin.4840829699554927414.pull-request-notifier-for-bitbucket-2.60_1490348837000.jar:na]
	at se.bjurr.prnfb.service.PrnfbVariable.resolve(PrnfbVariable.java:1359) ~[plugin.4840829699554927414.pull-request-notifier-for-bitbucket-2.60_1490348837000.jar:na]
	at se.bjurr.prnfb.service.PrnfbRenderer.renderVariable(PrnfbRenderer.java:133) [plugin.4840829699554927414.pull-request-notifier-for-bitbucket-2.60_1490348837000.jar:na]
	at se.bjurr.prnfb.service.PrnfbRenderer.render(PrnfbRenderer.java:117) [plugin.4840829699554927414.pull-request-notifier-for-bitbucket-2.60_1490348837000.jar:na]
	at se.bjurr.prnfb.listener.PrnfbPullRequestEventListener.notify(PrnfbPullRequestEventListener.java:230) [plugin.4840829699554927414.pull-request-notifier-for-bitbucket-2.60_1490348837000.jar:na]
	at se.bjurr.prnfb.service.ButtonsService.doHandlePressed(ButtonsService.java:108) [plugin.4840829699554927414.pull-request-notifier-for-bitbucket-2.60_1490348837000.jar:na]
	at se.bjurr.prnfb.service.ButtonsService.handlePressed(ButtonsService.java:160) [plugin.4840829699554927414.pull-request-notifier-for-bitbucket-2.60_1490348837000.jar:na]
	at se.bjurr.prnfb.presentation.ButtonServlet.press(ButtonServlet.java:172) [plugin.4840829699554927414.pull-request-notifier-for-bitbucket-2.60_1490348837000.jar:na]
`
 * Your configuration.

Injection URL: https://bamboo/rest/api/latest/plan/DA-DACMPN/branch/
Injection URL regexp: `/shortName="${PULL_REQUEST_FROM_BRANCH}" shortKey=["']([^'"]+)/g`

also tested

Injection URL: https://bamboo/rest/api/latest/plan/DA-DACMPN/branch/${PULL_REQUEST_FROM_BRANCH}
Injection URL regexp: `/shortKey=["']([^'"]+)/g`

this results in
`
fb.service.PrnfbRenderer Error when resolving INJECTION_URL_VALUE
java.lang.RuntimeException: java.net.URISyntaxException: Illegal character in path at index 66: https://bamboo/rest/api/latest/plan/DA-DACMPN/branch/${PULL_REQUEST_FROM_BRANCH}
`

**Comment by tomasbjerre** [comment]
Its in 2.61 now. Open issue again if any problems.

**Comment by schubter** [comment]
thanks, works perfectly
