### ISSUE TITLE
Unable to handle notification - after each PR change

### ISSUE THREAD

**Issue by marcin93** [tomasbjerre/pull-request-notifier-for-bitbucket#297]
Each time when within PR something to changing* _atlassian-bitbucket.log_ is getting error attached below. Before and after that time nothing happend.

(*) pr created, file commented, commit added, update: commit added/removed

* Plugin version used: 3.22
* Bitbucket Server version used: 5.8.2
* Stack traces in Bitbucket Server log file.

```
2018-08-30 11:33:40,397 ERROR [threadpool:thread-8] USERNAME *15AZXNBx693x1131547x1 lea8tm 10.1.16.55 "POST /rest/api/latest/projects/PROJECT/repos/NAME/pull-requests/287/comments HTTP/1.1" s.b.p.l.PrnfbPullRequestEventListener Unable to handle notification b667bf0b-64ad-4d5d-8a08-b6e55df86f70 NAME unit test job Jenkins GIT notification
java.lang.NullPointerException: Header value must be set
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226)
        at se.bjurr.prnfb.settings.PrnfbHeader.<init>(PrnfbHeader.java:14)
        at se.bjurr.prnfb.http.UrlInvoker.withHeader(UrlInvoker.java:231)
        at se.bjurr.prnfb.listener.PrnfbPullRequestEventListener.notify(PrnfbPullRequestEventListener.java:320)
        at se.bjurr.prnfb.listener.PrnfbPullRequestEventListener.handleEventNotification(PrnfbPullRequestEventListener.java:166)
        at se.bjurr.prnfb.listener.PrnfbPullRequestEventListener.handleEvent(PrnfbPullRequestEventListener.java:137)
        at se.bjurr.prnfb.listener.PrnfbPullRequestEventListener.access$000(PrnfbPullRequestEventListener.java:63)
        at se.bjurr.prnfb.listener.PrnfbPullRequestEventListener$2.run(PrnfbPullRequestEventListener.java:181)
        at com.atlassian.stash.internal.concurrent.DefaultTransferableStateManager$StateTransferringRunnable.run(DefaultTransferableStateManager.java:166)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.lang.Thread.run(Thread.java:745)
        ... 1 frame trimmed
```

* Configuration: ![pr_notifier_conf](https://user-images.githubusercontent.com/3214139/44905173-8e678b80-ad11-11e8-9a4c-572fdf53f82e.png)

**Comment by tomasbjerre** [comment]
Possible duplicate of: https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/issues/288

Your screenshot does not show any configured notification. In the dropdown under **Notifications** you have **New** selected. You probably have a notification there that has an empty value of a header configured.

**Comment by marcin93** [comment]
Exactly and that is surprising for me. I cannot change "New" to another value. But somehow addon is interacting with PR updates.

**Comment by tomasbjerre** [comment]
What do you get when browsing to: http://bitbucketdomain/rest/prnfb-admin/1.0/settings/notifications ?

**Comment by marcin93** [comment]
Related with this project:

`{"headers": [
{
"name": "Content-Type",
"value": "application/json"
}
],
"method": "POST",
"name": "Jenkins Git Notification",
"password": "KEEP_THIS_TO_LEAVE_UNCHANGED",
"postContent": "{\r\n    \"repository\": {\"name\": \"${PULL_REQUEST_TO_REPO_NAME}\"},\r\n    \"pr_to_branch\": \"${PULL_REQUEST_TO_BRANCH}\",\r\n    \"pr_from_sha1\": \"${PULL_REQUEST_FROM_HASH}\",\r\n    \"pr_url\": \"${PULL_REQUEST_URL}\",\r\n    \"pr_id\": \"${PULL_REQUEST_ID}\"\r\n}",
"projectKey": "PROJECT",
"proxyPassword": "KEEP_THIS_TO_LEAVE_UNCHANGED",
"proxyUser": "KEEP_THIS_TO_LEAVE_UNCHANGED",
"repositorySlug": "chipmodel",
"triggerIfCanMerge": "NOT_CONFLICTING",
"triggerIgnoreStateList": [
"DECLINED",
"MERGED"
],
"triggers": [
"OPENED",
"REOPENED",
"RESCOPED_FROM",
"RESCOPED_TO"
],
"updatePullRequestRefs": false,
"url": "http://HOST:8080/generic-webhook-trigger/invoke",
"user": "KEEP_THIS_TO_LEAVE_UNCHANGED",
"uuid": "eccceaaf-ddbb-4d98-add2-02b08539c050",
"postContentEncoding": "NONE",
"httpVersion": "HTTP_1_1"
},
{
"headers": [
{
"name": "Jenkins-Crumb",
"value": "${INJECTION_URL_VALUE}"
}
],
"injectionUrl": "http://HOST:8080/crumbIssuer/api/xml?xpath=//crumb",
"injectionUrlRegexp": "<crumb>([^<]*)</crumb>",
"method": "POST",
"name": "pybench unit test job Jenkins GIT notification",
"password": "KEEP_THIS_TO_LEAVE_UNCHANGED",
"projectKey": "PROJECT",
"proxyPassword": "KEEP_THIS_TO_LEAVE_UNCHANGED",
"proxyUser": "KEEP_THIS_TO_LEAVE_UNCHANGED",
"repositorySlug": "pybench",
"triggerIfCanMerge": "NOT_CONFLICTING",
"triggerIgnoreStateList": [
"DECLINED",
"MERGED"
],
"triggers": [
"OPENED",
"REOPENED",
"RESCOPED_FROM",
"RESCOPED_TO"
],
"updatePullRequestRefs": false,
"url": "http://HOST:8080/job/Pybench%20unit%20tests%20for%20pull%20request//buildWithParameters?token=6bWf32k3290e&cause=PULL_REQUEST&PULL_REQUEST_URL=${PULL_REQUEST_URL}&PULL_REQUEST_ID=${PULL_REQUEST_ID}&PULL_REQUEST_TO_BRANCH=${PULL_REQUEST_TO_BRANCH}&PULL_REQUEST_FROM_HASH=${PULL_REQUEST_FROM_HASH}",
"user": "KEEP_THIS_TO_LEAVE_UNCHANGED",
"uuid": "2c0d3a66-b41a-4288-bd6f-2937e37a89ec",
"postContentEncoding": "HTML"
},
{
"headers": [
{
"name": "Jenkins-Crumb",
"value": "${INJECTION_URL_VALUE}"
}
],
"injectionUrl": "http://HOST:8080/crumbIssuer/api/xml?xpath=//crumb",
"injectionUrlRegexp": "<crumb>([^<]*)</crumb>",
"method": "POST",
"name": "pybench unit test job Jenkins GIT notification",
"password": "KEEP_THIS_TO_LEAVE_UNCHANGED",
"projectKey": "PROJECT",
"proxyPassword": "KEEP_THIS_TO_LEAVE_UNCHANGED",
"proxyUser": "KEEP_THIS_TO_LEAVE_UNCHANGED",
"repositorySlug": "pybench",
"triggerIfCanMerge": "NOT_CONFLICTING",
"triggerIgnoreStateList": [
"DECLINED",
"MERGED"
],
"triggers": [
"COMMENTED",
"OPENED",
"REOPENED",
"RESCOPED_FROM",
"RESCOPED_TO"
],
"updatePullRequestRefs": false,
"url": "http://HOST:8080/job/Pybench%20unit%20tests%20for%20pull%20request//buildWithParameters?token=6bWf32k3290e&cause=PULL_REQUEST&PULL_REQUEST_URL=${PULL_REQUEST_URL}&PULL_REQUEST_ID=${PULL_REQUEST_ID}&PULL_REQUEST_TO_BRANCH=${PULL_REQUEST_TO_BRANCH}&PULL_REQUEST_FROM_HASH=${PULL_REQUEST_FROM_HASH}",
"user": "KEEP_THIS_TO_LEAVE_UNCHANGED",
"uuid": "b667bf0b-64ad-4d5d-8a08-b6e55df86f70",
"postContentEncoding": "HTML"
}`

**Comment by tomasbjerre** [comment]
You should be able to select **pybench unit test job Jenkins GIT notification** in the dropdown menu under **Notifications**.

**Comment by marcin93** [comment]
Right, but I don't want to have this notification set.

**Comment by tomasbjerre** [comment]
Select it, then click delete button?
