### ISSUE TITLE
Plugin stops when using https instead of http

### ISSUE THREAD

**Issue by bgofche** [tomasbjerre/pull-request-notifier-for-bitbucket#323]
Hello,

Recently migrated to trust certified https jenkins and trying to push pull requests through https url, but without success. When I turn back to http work as expected. Could be possible confict with reading https or wrong https port maybe, do I need to add in bitbucket in cacerts that trust cert? 

 * Plugin version - I'm not administrator
 * Bitbucket v4.14.0.

Configuration:
http://bitbucket/rest/prnfb-admin/1.0/settings/notifications
http://bitbucket/rest/prnfb-admin/1.0/settings/buttons

Jenkins is setup directly to use https (--httpsPort=8080) without https proxy.  

Also not able to find your plugin in atlassian page

**Comment by fredrikand** [comment]
Hi @bgofche ,

Who signed your certificate?
If your certificate was signed by for example your company CA, you have to complete the certificate trust chain by adding the Root and possible Issuing certificates to the cacert bundle used by Bitbucket.

**Comment by bgofche** [comment]
Hello @fredrikand,

Certificate sign by GoDaddy and get green bar and everything what is need to turn correct certificate.
I will try to import that certificate in the Bitbucket server java cacert file.

**Comment by bgofche** [comment]
This is what I found in the logs:

```
2019-03-25 11:49:16,390 ERROR [threadpool:thread-8] USERNAME @EPBWEYx709x3607097x96 11z96j6 IP-HIDDEN,IP-HIDDEN "POST /rest/api/latest/projects/****/repos/***********/pull-requests/99/comments HTTP/1.0" se.bjurr.prnfb.http.UrlInvoker
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
        at org.apache.http.impl.conn.BasicHttpClientConnectionManager.connect(BasicHttpClientConnectionManager.java:338)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
        at se.bjurr.prnfb.http.UrlInvoker.doInvoke(UrlInvoker.java:363)
        at se.bjurr.prnfb.http.UrlInvoker.invoke(UrlInvoker.java:169)
        at se.bjurr.prnfb.listener.PrnfbPullRequestEventListener$1.invoke(PrnfbPullRequestEventListener.java:94)
        at se.bjurr.prnfb.listener.PrnfbPullRequestEventListener.notify(PrnfbPullRequestEventListener.java:277)
        at se.bjurr.prnfb.listener.PrnfbPullRequestEventListener.handleEvent(PrnfbPullRequestEventListener.java:119)
        at se.bjurr.prnfb.listener.PrnfbPullRequestEventListener.access$000(PrnfbPullRequestEventListener.java:57)
        at se.bjurr.prnfb.listener.PrnfbPullRequestEventListener$2.run(PrnfbPullRequestEventListener.java:135)
        at com.atlassian.stash.internal.concurrent.StateTransferringExecutor$StateTransferringRunnable.run(StateTransferringExecutor.java:70)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.lang.Thread.run(Thread.java:748)
        ... 1 frame trimmed
```

**Comment by bgofche** [comment]
Seems that is issue from GoDaddy. In order to work your trusted certificate correctly use that method:
```
wget https://ssl-ccp.godaddy.com/repository/gd_bundle-g2-g1.crt
cat mytrust.crt gd_bundle-g2-g1.crt >> mytrust-chained.crt
```

And after that you can include it or generate *.p12 or keystore.
