### ISSUE TITLE
Unable to create button

### ISSUE THREAD

**Issue by jay00929** [tomasbjerre/pull-request-notifier-for-bitbucket#344]
If things don't work as you expect, perhaps you should file an issue. But first, try troubleshooting it and provide as much info as possible. Here are some things that may help if added to an issue.

 * Plugin version used.
 * Bitbucket Server version used.
 * Stack traces in Bitbucket Server log file.
 * Any browser console log messages, you can find it in Developer Tools in Chome by pressing F12.
 * Your configuration:
   * http://localhost:7990/bitbucket/rest/prnfb-admin/1.0/settings
   * http://localhost:7990/bitbucket/rest/prnfb-admin/1.0/settings/buttons
   * http://localhost:7990/bitbucket/rest/prnfb-admin/1.0/settings/notifications
 * If the system you are trying to notify does not seem to get notified:
  * Check that the triggered URL looks as expected. You can do that by invoking https://requestb.in/ and inspect its results.
  * Try to SSH to the Bitbucket Server machine and run same URL with Curl to make sure it's not a firewall issue.
  * Enable runtime debug logging of 'se.bjurr.prnfb.http.UrlInvoker' following https://confluence.atlassian.com/bitbucketserver/bitbucket-server-debug-logging-776640147.html

If you do not have access to the server log files, one idea is to:

 * Also trigger on button pressed, and add a button
 * Open a PR
 * Open Chrome developer tools, F12
 * Press the button in the PR
 * Check the response in the network tab in Chrome. See if it contains something interesting

**Comment by jay00929** [comment]
By using pull-request-notifier-for-bitbucket plugin, we are trying to create a new button in pull request view to enable the notification method and to triggered a new event. Same we already did back and that was working fine. While today when we are trying to enable a new button in different repository, message appears success but unable to view that button in any pull request. I can see below error in my atlassian-bitbucket.log:

2019-08-08 19:01:45,705 ERROR [http-nio-7990-exec-39] jayprakash.singh @ZYIE8Jx1141x8216400x1 1ftanqm 136.232.1.30,127.0.0.1 "GET /rest/prnfb-admin/1.0/settings/buttons/repository/674/pullrequest/3 HTTP/1.0" c.a.p.r.c.e.j.ThrowableExceptionMapper Uncaught exception thrown by REST service: Unable to build keystore from /opt/atlassian/bitbucket/5.13.1/bin/jayprakash.singh
java.lang.RuntimeException: Unable to build keystore from /opt/atlassian/bitbucket/5.13.1/bin/jayprakash.singh
at se.bjurr.prnfb.http.ClientKeyStore.(ClientKeyStore.java:36)
at se.bjurr.prnfb.service.ButtonsService.getButtons(ButtonsService.java:125)
at se.bjurr.prnfb.presentation.ButtonServlet.get(ButtonServlet.java:150)
at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
at com.atlassian.analytics.client.filter.UniversalAnalyticsFilter.doFilter(UniversalAnalyticsFilter.java:92)
at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:39)
at com.atlassian.bitbucket.internal.xcode.web.XcodeUserAgentFilter.doFilter(XcodeUserAgentFilter.java:36)
