### ISSUE TITLE
Bamboo setup question.

### ISSUE THREAD

**Issue by RaviFIS** [tomasbjerre/pull-request-notifier-for-bitbucket#98]
Hello 

I am not sure if i can use this plugin to  integrate with bamboo.  I am giving it a try.

First i tried to Trigger button to be accessible by everyone.  It is not showing up under pull request.
Second i not sure why this plugin is not appearing as  post webhook under hooks section of the git repository.

Also i tried to pass the value like this  based on the example provided in the document.

http://vlbamboo1.atldev.com:8080/rest/api/latest/queue/EAD-DEVPULLREQ?bamboo.PULL_REQUEST_ID=${PULL_REQUEST_ID}

I have the following Trigger condition :  Commented, updated. created.  Some how changes to pull request is not kicking off bamboo build  

Can you please tell me what am i missing in the configuration ?

Best regards
Ravi.

**Comment by RaviFIS** [comment]
I got the Button to show up in the pull request   However i am receiving the following message

java.io.FileNotFoundException: http://vlbamboo1.atldev.com:8080/rest/api/latest/queue/EAD-DEVPULLREQ?bamboo.variable.blah=blahblah
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1835) ~[na:1.8.0_45]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440) ~[na:1.8.0_45]
        at se.bjurr.prnfs.listener.UrlInvoker.invoke(UrlInvoker.java:117) ~[plugin_7624430298786718683_pull-request-notifier-for-stash-1.37_1454629323000.jar:na]
        at se.bjurr.prnfs.listener.PrnfsPullRequestEventListener$1.invoke(PrnfsPullRequestEventListener.java:64) [plugin_7624430298786718683_pull-request-notifier-for-stash-1.37_1454629323000.jar:na]
        at se.bjurr.prnfs.listener.PrnfsPullRequestEventListener.notify(PrnfsPullRequestEventListener.java:203) [plugin_7624430298786718683_pull-request-notifier-for-stash-1.37_1454629323000.jar:na]
        at se.bjurr.prnfs.ManualResource.post(ManualResource.java:140) [plugin_7624430298786718683_pull-request-notifier-for-stash-1.37_1454629323000.jar:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:25) [applinks-plugin-4.3.7_1433820634000.jar:na]
        at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:88) [StashAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:111) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:77) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:103) [atlassian-trusted-apps-core-4.0.0.jar:na]
        at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:79) [atlassian-oauth-service-provider-plugin-1.9.10_1433820634000.jar:na]
        at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:32) [analytics-client-3.65.1_1433820636000.jar:na]
        at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32) [analytics-client-3.65.1_1433820636000.jar:na]
        at com.atlassian.stash.internal.web.StreamGuardFilter.doFilter(StreamGuardFilter.java:49) [stash-stream-guard-plugin-1.0.1.jar:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:89) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:85) [stash-service-impl-3.10.0.jar:na]
        at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38) [ConfigurableWebFilter.class:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
        ... 207 frames trimmed

**Comment by tomasbjerre** [comment]
Can you browse to
http://vlbamboo1.atldev.com:8080/rest/api/latest/queue/EAD-DEVPULLREQ?bamboo.variable.blah=blahblah
from the machine running Stash?
Den 5 feb 2016 00:50 skrev "RaviFIS" <notifications@github.com>:

**Comment by RaviFIS** [comment]
Thanks for the response. I figured out the problem.  My URL information was wrong. Once i fixed that  plugin is working as designed.

Ravi.

**Comment by tomasbjerre** [comment]
Nice :)

**Comment by RaviFIS** [comment]
I still have one problem with the current setup .  Pull requests build that i setup is triggering for every commit in various git repository 

>>Second i not sure why this plugin is not appearing as post webhook under hooks section of the git repository.

How can i make the webhook to work only for the bitbucket project that i am interested in ?

Thanks
Ravi.

**Comment by tomasbjerre** [comment]
Use the filter feature. You can have this as the string:
${PULL_REQUEST_FROM_REPO_SLUG}
An the regexp would just be the name of your project.

If you look at the plugin in Marketplace. This is on one of the
screenshots, but there I use a repo variable.
Den 5 feb 2016 16:42 skrev "RaviFIS" <notifications@github.com>:

**Comment by RaviFIS** [comment]
Thanks 

I added that variable and that seems to apply to the git project i am interested in.  I tried to bring up the regexp url  but it times out.

I tried to apply the trigger against multiple repos like  gitRepoA,gitRepoB  ( is comma separated regex values are allowed ?)

Ravi.

**Comment by tomasbjerre** [comment]
No, use pipe. Like: gitRepoA|gitRepoB or just do gitRepo.*
Den 5 feb 2016 17:19 skrev "RaviFIS" <notifications@github.com>:

**Comment by RaviFIS** [comment]
Cool

Some of the git repos have spaces in their names  Let's say if thre is a git repo by name "gitRepo A" 

As you can see i am passing the value like shown below should the passing value be quoted to escape the space in the repository ?

bamboo.variable.gitrepo="${PULL_REQUEST_FROM_REPO_NAME}"

http://vlbamboo1.atldev.com:8080/rest/api/latest/queue/EAD-DEVPULLREQ?bamboo.variable.prid=${PULL_REQUEST_ID}&bamboo.variable.prjkey=${PULL_REQUEST_FROM_REPO_PROJECT_KEY}&bamboo.variable.gitrepo=${PULL_REQUEST_FROM_REPO_NAME}

**Comment by tomasbjerre** [comment]
No it will be url-encoded so no problem.

**Comment by RaviFIS** [comment]
Appreciate all your response . This plugin will be very helpful for our Agile team when we roll out into production.

Ravi.

**Comment by RaviFIS** [comment]
tomasbjerre

I am facing another issue  here.  Trigger button is not appearing in pull request.

when i tested this i was working with one git repository.  I have created hook for each repository as a requirement and also need to enable the  Trigger for that pull request.

Assume i need to use ${BUTTON_TRIGGER_TITLE} to make the button show up in pull request.

How can i pass that info along with git repository information

Can it be like ${PULL_REQUEST_FROM_REPO_SLUG},${BUTTON_TRIGGER_TITLE} ?
value as RepoA|sonarscan ?

Thanks
Ravi.

**Comment by RaviFIS** [comment]
Never mind i found out that I did not enable Button_trigger check box.

Thanks
Ravi.

**Comment by RaviFIS** [comment]
For some reason I am not able to Trigger a build when Pull request is updated.

I am capturing PULL_REQUEST_ACTION  and i can get  OPENED and BUTTON_TRIGGER  event .

But when i made file changes that updated the PR with new commits which did not trigger the build. Should  i need to do anything differently to capture the event ?

Thanks
Ravi.

**Comment by tomasbjerre** [comment]
The rescoped events are triggered when files are changed in the pull
request.
Den 18 feb 2016 00:13 skrev "RaviFIS" <notifications@github.com>:

**Comment by RaviFIS** [comment]
That was it...

I was under the impression just selecting the "Updated" was enough to trigger the builds.

Once i added RESCOPED_FROM and RESCOPED_TO  things seems to be working as designed.

Should we need to add both the conditions of RESCOPE ?

Thanks
Ravi.

**Comment by tomasbjerre** [comment]
Hi!

I added a description on how to use the plugin with HipChat here:
https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket/blob/master/README_hipchat.md
And referred to it from the main readme under "Integration guides".

Would be nice if you can write up something on how you integrate it with Bamboo.
